"""initial schema

Revision ID: 112e0a2d4791
Revises: 
Create Date: 2026-06-29 18:19:18.628205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112e0a2d4791'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelter_name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('maximum_capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role_level', sa.Enum('super_admin', 'gov_officer', 'field_officer', 'citizen'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'needs_verification', 'verified', 'rejected'), nullable=False),
    sa.Column('assigned_node_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('allocated_shelter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allocated_shelter_id'], ['shelters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identification_number')
    )
    op.create_table('inventory_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('sku_name', sa.String(length=120), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('metric_unit', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_shelter_id', sa.Integer(), nullable=False),
    sa.Column('requested_sku', sa.String(length=120), nullable=False),
    sa.Column('quantity_needed', sa.Integer(), nullable=False),
    sa.Column('status_state', sa.Enum('pending', 'approved', 'fulfilled', 'rejected'), nullable=True),
    sa.Column('fulfilled_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fulfilled_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['origin_shelter_id'], ['shelters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procurement_requests')
    op.drop_table('inventory_stock')
    op.drop_table('beneficiaries')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('shelters')
    # ### end Alembic commands ###
