"""add location fields to beneficiary

Revision ID: a03957d9c2ba
Revises: f3a8c1d2e6b7
Create Date: 2026-07-20 11:20:18.463883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03957d9c2ba'
down_revision = 'f3a8c1d2e6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('location_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_column('location_verified')
        batch_op.drop_column('location_updated_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
